env:
    CONFIG: env.conf
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    CIRRUS_SHELL: bash
    rlslone_config: "ENCRYPTED[!a9d398427093852505ac79c60913e2f31fe41c4d1f3c829044f4d81301e15c9cf27a3e44c924fbe09c0882bffaa05f3d!]"
    GIT_TOKEN: "ENCRYPTED[!eaf159ede8934df6bfb1b2d13f91bfcccc596a9350c132cde48891710977a9294881549b8bc992ebbe8343c9ba80ab92!]"
    TG_TOKEN: "ENCRYPTED[!a5aad29f3e9c92a7ac52b921ebc4d89ed24a6ceeb43b6f58e7a7a54a702dfa27a62069a96e720d0bf6d95ca4d253dd83!]"
    CCACHE_INDEX_DOWNLOAD_URL: "ENCRYPTED[!f5cf7f6c075e217a9ee24f71f4fc1589fe11b364ee2eb4413b4e277b1b97834cd87e3e97d7d7188fddd945339d0a8191!]"
    GIT_COOKIES_RAW_GIST: "ENCRYPTED[!bb2c0fb2f18891c5b70a0b9ef428d84388dcc94fa95848ed2ea7aac1e2f3cb999df885989f5016536732a84558a5b482!]"

    
task:
    name: Build
    timeout_in: 2h
    container:
      image: madhavsheth/android_build_environment:latest
      cpu: 8
      memory: 32g
      greedy: true
    
    setupcc_script:
      - SECONDS=0
      - bash privatize_repo.sh
      - if [[ "$(tail -1 download_ccache.sh)" -ge "10" ]]; then echo "Build Failed!" && exit 1; fi
      - if [[ "$(tail -1 download_ccache.sh)" == "CCACHE_RUN=0" ]]; then echo 'skip ccache'; else bash download_ccache.sh ; fi
      - echo $SECONDS > /tmp/ci/seconds.txt
    additional_script:
      - SECONDS=$(< /tmp/ci/seconds.txt)
      - bash additional.sh || true
      - echo $SECONDS > /tmp/ci/seconds.txt
    sync_script:
      - SECONDS=$(< /tmp/ci/seconds.txt)
      - if ! timeout 30m bash sync.sh; then bash publisize_repo.sh && bash retry_sync.sh; fi
      - echo $SECONDS > /tmp/ci/seconds.txt
      - echo "Sync Took "$(($SECONDS / 60))"m to execute"
    patch_script:
      - SECONDS=$(< /tmp/ci/seconds.txt)
      - bash patch.sh
      - echo $SECONDS > /tmp/ci/seconds.txt
    build_script:
      - chmod a+x retry_cleanbuild.sh
      - SECONDS=$(< /tmp/ci/seconds.txt)
      - echo "Build Timeout in "$(( $((6660 - $SECONDS)) / 60 ))"m"
      - bash build.sh
      - echo $SECONDS > /tmp/ci/seconds.txt
    ccupload_script:
      - bash upload_ccache.sh
    telegram_script:
      - bash tg.sh || true
